site_name: AI Impact Library

theme:
  name: material
  logo: logofolder/Logo-Immanence-Vector.svg


  font: 
  text: instrument sans
  code: roboto mono

extra_css:
  - stylesheets/extra.css

nav:
  - Home: index.md

  - Explore Impacts:
      - AI-Assisted Software Development: impacts/IMP-0001-ai-assisted-software-development.md

  - Taxonomy:
      - AI Capabilities: taxonomy/ai-capabilities.md
      - Ethical Dimensions: taxonomy/ethical-dimensions.md
      - Polarity: taxonomy/polarity.md
      - Stakeholders: taxonomy/stakeholders.md
      - Time Horizon: taxonomy/time-horizon.md
      - Evidence Level: taxonomy/evidence-level.md
      - Confidence Level: taxonomy/confidence-level.md
      - Impact Severity: taxonomy/impact-severity.md
      - Adoption Level: taxonomy/adoption-level.md

  - About:
      - Project Overview: about.md
